// Typedefs and Constants

export type PropertyTypeTag = number;
export type vrshared_uint64 = bigint;
export type vrshared_double = number;
export type SpatialAnchorHandle = number;
export type glSharedTextureHandle = Deno.PointerValue;
export type glInt = number;
export type glUInt = number;
export type SharedTextureHandle = bigint;
export type DriverId = number;
export type TrackedDeviceIndex = number;
export type WebConsoleHandle = bigint;
export type PropertyContainerHandle = bigint;
export type PropertyTypeTag = number;
export type DriverHandle = PropertyContainerHandle;
export type ActionHandle = bigint;
export type ActionSetHandle = bigint;
export type InputValueHandle = bigint;
export type ComponentProperties = number;
export type ControllerState = ControllerState001;
export type OverlayHandle = bigint;
export type BoneIndex = number;
export type TrackedCameraHandle = bigint;
export type ScreenshotHandle = number;
export type TextureID = number;
export type NotificationId = number;
export type IOBufferHandle = bigint;
export type VrProfilerEventHandle = bigint;
export type HmdError = InitError;
export type Hmd_Eye = Eye;
export type HmdTrackingResult = TrackingResult;
export type ScreenshotsError = ScreenshotError;
export type PathHandle = bigint;

export const k_nDriverNone: number = 4294967295;//uint32_t
export const k_unMaxDriverDebugResponseSize: number = 32768;//uint32_t
export const k_unTrackedDeviceIndex_Hmd: number = 0;//uint32_t
export const k_unMaxTrackedDeviceCount: number = 64;//uint32_t
export const k_unTrackedDeviceIndexOther: number = 4294967294;//uint32_t
export const k_unTrackedDeviceIndexInvalid: number = 4294967295;//uint32_t
export const k_ulInvalidPropertyContainer: PropertyContainerHandle = 0n;//uint64_t
export const k_unInvalidPropertyTag: PropertyTypeTag = 0;//uint32_t
export const k_ulInvalidDriverHandle: PropertyContainerHandle = 0n;//uint64_t
export const k_unFloatPropertyTag: PropertyTypeTag = 1;//uint32_t
export const k_unInt32PropertyTag: PropertyTypeTag = 2;//uint32_t
export const k_unUint64PropertyTag: PropertyTypeTag = 3;//uint32_t
export const k_unBoolPropertyTag: PropertyTypeTag = 4;//uint32_t
export const k_unStringPropertyTag: PropertyTypeTag = 5;//uint32_t
export const k_unErrorPropertyTag: PropertyTypeTag = 6;//uint32_t
export const k_unDoublePropertyTag: PropertyTypeTag = 7;//uint32_t
export const k_unHmdMatrix34PropertyTag: PropertyTypeTag = 20;//uint32_t
export const k_unHmdMatrix44PropertyTag: PropertyTypeTag = 21;//uint32_t
export const k_unHmdVector3PropertyTag: PropertyTypeTag = 22;//uint32_t
export const k_unHmdVector4PropertyTag: PropertyTypeTag = 23;//uint32_t
export const k_unHmdVector2PropertyTag: PropertyTypeTag = 24;//uint32_t
export const k_unHmdQuadPropertyTag: PropertyTypeTag = 25;//uint32_t
export const k_unHiddenAreaPropertyTag: PropertyTypeTag = 30;//uint32_t
export const k_unPathHandleInfoTag: PropertyTypeTag = 31;//uint32_t
export const k_unActionPropertyTag: PropertyTypeTag = 32;//uint32_t
export const k_unInputValuePropertyTag: PropertyTypeTag = 33;//uint32_t
export const k_unWildcardPropertyTag: PropertyTypeTag = 34;//uint32_t
export const k_unHapticVibrationPropertyTag: PropertyTypeTag = 35;//uint32_t
export const k_unSkeletonPropertyTag: PropertyTypeTag = 36;//uint32_t
export const k_unSpatialAnchorPosePropertyTag: PropertyTypeTag = 40;//uint32_t
export const k_unJsonPropertyTag: PropertyTypeTag = 41;//uint32_t
export const k_unActiveActionSetPropertyTag: PropertyTypeTag = 42;//uint32_t
export const k_unOpenVRInternalReserved_Start: PropertyTypeTag = 1000;//uint32_t
export const k_unOpenVRInternalReserved_End: PropertyTypeTag = 10000;//uint32_t
export const k_unMaxPropertyStringSize: number = 32768;//uint32_t
export const k_ulInvalidActionHandle: ActionHandle = 0n;//uint64_t
export const k_ulInvalidActionSetHandle: ActionSetHandle = 0n;//uint64_t
export const k_ulInvalidInputValueHandle: InputValueHandle = 0n;//uint64_t
export const k_unControllerStateAxisCount: number = 5;//uint32_t
export const k_ulOverlayHandleInvalid: OverlayHandle = 0n;//uint64_t
export const k_unMaxDistortionFunctionParameters: number = 8;//uint32_t
export const k_unScreenshotHandleInvalid: number = 0;//uint32_t
export const IVRSystem_Version: string = "FnTable:IVRSystem_022";//char *const
export const IVRExtendedDisplay_Version: string = "FnTable:IVRExtendedDisplay_001";//char *const
export const IVRTrackedCamera_Version: string = "FnTable:IVRTrackedCamera_006";//char *const
export const k_unMaxApplicationKeyLength: number = 128;//uint32_t
export const k_pch_MimeType_HomeApp: string = "vr/home";//char *const
export const k_pch_MimeType_GameTheater: string = "vr/game_theater";//char *const
export const IVRApplications_Version: string = "FnTable:IVRApplications_007";//char *const
export const IVRChaperone_Version: string = "FnTable:IVRChaperone_004";//char *const
export const IVRChaperoneSetup_Version: string = "FnTable:IVRChaperoneSetup_006";//char *const
export const IVRCompositor_Version: string = "FnTable:IVRCompositor_028";//char *const
export const k_unVROverlayMaxKeyLength: number = 128;//uint32_t
export const k_unVROverlayMaxNameLength: number = 128;//uint32_t
export const k_unMaxOverlayCount: number = 128;//uint32_t
export const k_unMaxOverlayIntersectionMaskPrimitivesCount: number = 32;//uint32_t
export const IVROverlay_Version: string = "FnTable:IVROverlay_027";//char *const
export const IVROverlayView_Version: string = "FnTable:IVROverlayView_003";//char *const
export const k_unHeadsetViewMaxWidth: number = 3840;//uint32_t
export const k_unHeadsetViewMaxHeight: number = 2160;//uint32_t
export const k_pchHeadsetViewOverlayKey: string = "system.HeadsetView";//char *const
export const IVRHeadsetView_Version: string = "FnTable:IVRHeadsetView_001";//char *const
export const k_pch_Controller_Component_GDC2015: string = "gdc2015";//char *const
export const k_pch_Controller_Component_Base: string = "base";//char *const
export const k_pch_Controller_Component_Tip: string = "tip";//char *const
export const k_pch_Controller_Component_OpenXR_Aim: string = "openxr_aim";//char *const
export const k_pch_Controller_Component_HandGrip: string = "handgrip";//char *const
export const k_pch_Controller_Component_OpenXR_Grip: string = "openxr_grip";//char *const
export const k_pch_Controller_Component_OpenXR_HandModel: string = "openxr_handmodel";//char *const
export const k_pch_Controller_Component_Status: string = "status";//char *const
export const IVRRenderModels_Version: string = "FnTable:IVRRenderModels_006";//char *const
export const k_unNotificationTextMaxSize: number = 256;//uint32_t
export const IVRNotifications_Version: string = "FnTable:IVRNotifications_002";//char *const
export const k_unMaxSettingsKeyLength: number = 128;//uint32_t
export const IVRSettings_Version: string = "FnTable:IVRSettings_003";//char *const
export const k_pch_SteamVR_Section: string = "steamvr";//char *const
export const k_pch_SteamVR_RequireHmd_String: string = "requireHmd";//char *const
export const k_pch_SteamVR_ForcedDriverKey_String: string = "forcedDriver";//char *const
export const k_pch_SteamVR_ForcedHmdKey_String: string = "forcedHmd";//char *const
export const k_pch_SteamVR_DisplayDebug_Bool: string = "displayDebug";//char *const
export const k_pch_SteamVR_DebugProcessPipe_String: string = "debugProcessPipe";//char *const
export const k_pch_SteamVR_DisplayDebugX_Int32: string = "displayDebugX";//char *const
export const k_pch_SteamVR_DisplayDebugY_Int32: string = "displayDebugY";//char *const
export const k_pch_SteamVR_SendSystemButtonToAllApps_Bool: string = "sendSystemButtonToAllApps";//char *const
export const k_pch_SteamVR_LogLevel_Int32: string = "loglevel";//char *const
export const k_pch_SteamVR_IPD_Float: string = "ipd";//char *const
export const k_pch_SteamVR_Background_String: string = "background";//char *const
export const k_pch_SteamVR_BackgroundUseDomeProjection_Bool: string = "backgroundUseDomeProjection";//char *const
export const k_pch_SteamVR_BackgroundCameraHeight_Float: string = "backgroundCameraHeight";//char *const
export const k_pch_SteamVR_BackgroundDomeRadius_Float: string = "backgroundDomeRadius";//char *const
export const k_pch_SteamVR_GridColor_String: string = "gridColor";//char *const
export const k_pch_SteamVR_PlayAreaColor_String: string = "playAreaColor";//char *const
export const k_pch_SteamVR_TrackingLossColor_String: string = "trackingLossColor";//char *const
export const k_pch_SteamVR_ShowStage_Bool: string = "showStage";//char *const
export const k_pch_SteamVR_DrawTrackingReferences_Bool: string = "drawTrackingReferences";//char *const
export const k_pch_SteamVR_ActivateMultipleDrivers_Bool: string = "activateMultipleDrivers";//char *const
export const k_pch_SteamVR_UsingSpeakers_Bool: string = "usingSpeakers";//char *const
export const k_pch_SteamVR_SpeakersForwardYawOffsetDegrees_Float: string = "speakersForwardYawOffsetDegrees";//char *const
export const k_pch_SteamVR_BaseStationPowerManagement_Int32: string = "basestationPowerManagement";//char *const
export const k_pch_SteamVR_ShowBaseStationPowerManagementTip_Int32: string = "ShowBaseStationPowerManagementTip";//char *const
export const k_pch_SteamVR_NeverKillProcesses_Bool: string = "neverKillProcesses";//char *const
export const k_pch_SteamVR_SupersampleScale_Float: string = "supersampleScale";//char *const
export const k_pch_SteamVR_MaxRecommendedResolution_Int32: string = "maxRecommendedResolution";//char *const
export const k_pch_SteamVR_MotionSmoothing_Bool: string = "motionSmoothing";//char *const
export const k_pch_SteamVR_MotionSmoothingOverride_Int32: string = "motionSmoothingOverride";//char *const
export const k_pch_SteamVR_FramesToThrottle_Int32: string = "framesToThrottle";//char *const
export const k_pch_SteamVR_AdditionalFramesToPredict_Int32: string = "additionalFramesToPredict";//char *const
export const k_pch_SteamVR_WorldScale_Float: string = "worldScale";//char *const
export const k_pch_SteamVR_FovScale_Int32: string = "fovScale";//char *const
export const k_pch_SteamVR_FovScaleLetterboxed_Bool: string = "fovScaleLetterboxed";//char *const
export const k_pch_SteamVR_DisableAsyncReprojection_Bool: string = "disableAsync";//char *const
export const k_pch_SteamVR_ForceFadeOnBadTracking_Bool: string = "forceFadeOnBadTracking";//char *const
export const k_pch_SteamVR_DefaultMirrorView_Int32: string = "mirrorView";//char *const
export const k_pch_SteamVR_ShowLegacyMirrorView_Bool: string = "showLegacyMirrorView";//char *const
export const k_pch_SteamVR_MirrorViewVisibility_Bool: string = "showMirrorView";//char *const
export const k_pch_SteamVR_MirrorViewDisplayMode_Int32: string = "mirrorViewDisplayMode";//char *const
export const k_pch_SteamVR_MirrorViewEye_Int32: string = "mirrorViewEye";//char *const
export const k_pch_SteamVR_MirrorViewGeometry_String: string = "mirrorViewGeometry";//char *const
export const k_pch_SteamVR_MirrorViewGeometryMaximized_String: string = "mirrorViewGeometryMaximized";//char *const
export const k_pch_SteamVR_PerfGraphVisibility_Bool: string = "showPerfGraph";//char *const
export const k_pch_SteamVR_StartMonitorFromAppLaunch: string = "startMonitorFromAppLaunch";//char *const
export const k_pch_SteamVR_StartCompositorFromAppLaunch_Bool: string = "startCompositorFromAppLaunch";//char *const
export const k_pch_SteamVR_StartDashboardFromAppLaunch_Bool: string = "startDashboardFromAppLaunch";//char *const
export const k_pch_SteamVR_StartOverlayAppsFromDashboard_Bool: string = "startOverlayAppsFromDashboard";//char *const
export const k_pch_SteamVR_EnableHomeApp: string = "enableHomeApp";//char *const
export const k_pch_SteamVR_CycleBackgroundImageTimeSec_Int32: string = "CycleBackgroundImageTimeSec";//char *const
export const k_pch_SteamVR_RetailDemo_Bool: string = "retailDemo";//char *const
export const k_pch_SteamVR_IpdOffset_Float: string = "ipdOffset";//char *const
export const k_pch_SteamVR_AllowSupersampleFiltering_Bool: string = "allowSupersampleFiltering";//char *const
export const k_pch_SteamVR_SupersampleManualOverride_Bool: string = "supersampleManualOverride";//char *const
export const k_pch_SteamVR_EnableLinuxVulkanAsync_Bool: string = "enableLinuxVulkanAsync";//char *const
export const k_pch_SteamVR_AllowDisplayLockedMode_Bool: string = "allowDisplayLockedMode";//char *const
export const k_pch_SteamVR_HaveStartedTutorialForNativeChaperoneDriver_Bool: string = "haveStartedTutorialForNativeChaperoneDriver";//char *const
export const k_pch_SteamVR_ForceWindows32bitVRMonitor: string = "forceWindows32BitVRMonitor";//char *const
export const k_pch_SteamVR_DebugInputBinding: string = "debugInputBinding";//char *const
export const k_pch_SteamVR_DoNotFadeToGrid: string = "doNotFadeToGrid";//char *const
export const k_pch_SteamVR_EnableSharedResourceJournaling: string = "enableSharedResourceJournaling";//char *const
export const k_pch_SteamVR_EnableSafeMode: string = "enableSafeMode";//char *const
export const k_pch_SteamVR_PreferredRefreshRate: string = "preferredRefreshRate";//char *const
export const k_pch_SteamVR_LastVersionNotice: string = "lastVersionNotice";//char *const
export const k_pch_SteamVR_LastVersionNoticeDate: string = "lastVersionNoticeDate";//char *const
export const k_pch_SteamVR_HmdDisplayColorGainR_Float: string = "hmdDisplayColorGainR";//char *const
export const k_pch_SteamVR_HmdDisplayColorGainG_Float: string = "hmdDisplayColorGainG";//char *const
export const k_pch_SteamVR_HmdDisplayColorGainB_Float: string = "hmdDisplayColorGainB";//char *const
export const k_pch_SteamVR_CustomIconStyle_String: string = "customIconStyle";//char *const
export const k_pch_SteamVR_CustomOffIconStyle_String: string = "customOffIconStyle";//char *const
export const k_pch_SteamVR_CustomIconForceUpdate_String: string = "customIconForceUpdate";//char *const
export const k_pch_SteamVR_AllowGlobalActionSetPriority: string = "globalActionSetPriority";//char *const
export const k_pch_SteamVR_OverlayRenderQuality: string = "overlayRenderQuality_2";//char *const
export const k_pch_SteamVR_BlockOculusSDKOnOpenVRLaunchOption_Bool: string = "blockOculusSDKOnOpenVRLaunchOption";//char *const
export const k_pch_SteamVR_BlockOculusSDKOnAllLaunches_Bool: string = "blockOculusSDKOnAllLaunches";//char *const
export const k_pch_SteamVR_HDCPLegacyCompatibility_Bool: string = "hdcp14legacyCompatibility";//char *const
export const k_pch_SteamVR_DisplayPortTrainingMode_Int: string = "displayPortTrainingMode";//char *const
export const k_pch_SteamVR_UsePrism_Bool: string = "usePrism";//char *const
export const k_pch_SteamVR_AllowFallbackMirrorWindowLinux_Bool: string = "allowFallbackMirrorWindowLinux";//char *const
export const k_pch_OpenXR_Section: string = "openxr";//char *const
export const k_pch_OpenXR_MetaUnityPluginCompatibility_Int32: string = "metaUnityPluginCompatibility";//char *const
export const k_pch_DirectMode_Section: string = "direct_mode";//char *const
export const k_pch_DirectMode_Enable_Bool: string = "enable";//char *const
export const k_pch_DirectMode_Count_Int32: string = "count";//char *const
export const k_pch_DirectMode_EdidVid_Int32: string = "edidVid";//char *const
export const k_pch_DirectMode_EdidPid_Int32: string = "edidPid";//char *const
export const k_pch_Lighthouse_Section: string = "driver_lighthouse";//char *const
export const k_pch_Lighthouse_DisableIMU_Bool: string = "disableimu";//char *const
export const k_pch_Lighthouse_DisableIMUExceptHMD_Bool: string = "disableimuexcepthmd";//char *const
export const k_pch_Lighthouse_UseDisambiguation_String: string = "usedisambiguation";//char *const
export const k_pch_Lighthouse_DisambiguationDebug_Int32: string = "disambiguationdebug";//char *const
export const k_pch_Lighthouse_PrimaryBasestation_Int32: string = "primarybasestation";//char *const
export const k_pch_Lighthouse_DBHistory_Bool: string = "dbhistory";//char *const
export const k_pch_Lighthouse_EnableBluetooth_Bool: string = "enableBluetooth";//char *const
export const k_pch_Lighthouse_PowerManagedBaseStations_String: string = "PowerManagedBaseStations";//char *const
export const k_pch_Lighthouse_PowerManagedBaseStations2_String: string = "PowerManagedBaseStations2";//char *const
export const k_pch_Lighthouse_InactivityTimeoutForBaseStations_Int32: string = "InactivityTimeoutForBaseStations";//char *const
export const k_pch_Lighthouse_EnableImuFallback_Bool: string = "enableImuFallback";//char *const
export const k_pch_Null_Section: string = "driver_null";//char *const
export const k_pch_Null_SerialNumber_String: string = "serialNumber";//char *const
export const k_pch_Null_ModelNumber_String: string = "modelNumber";//char *const
export const k_pch_Null_WindowX_Int32: string = "windowX";//char *const
export const k_pch_Null_WindowY_Int32: string = "windowY";//char *const
export const k_pch_Null_WindowWidth_Int32: string = "windowWidth";//char *const
export const k_pch_Null_WindowHeight_Int32: string = "windowHeight";//char *const
export const k_pch_Null_RenderWidth_Int32: string = "renderWidth";//char *const
export const k_pch_Null_RenderHeight_Int32: string = "renderHeight";//char *const
export const k_pch_Null_SecondsFromVsyncToPhotons_Float: string = "secondsFromVsyncToPhotons";//char *const
export const k_pch_Null_DisplayFrequency_Float: string = "displayFrequency";//char *const
export const k_pch_WindowsMR_Section: string = "driver_holographic";//char *const
export const k_pch_UserInterface_Section: string = "userinterface";//char *const
export const k_pch_UserInterface_StatusAlwaysOnTop_Bool: string = "StatusAlwaysOnTop";//char *const
export const k_pch_UserInterface_MinimizeToTray_Bool: string = "MinimizeToTray";//char *const
export const k_pch_UserInterface_HidePopupsWhenStatusMinimized_Bool: string = "HidePopupsWhenStatusMinimized";//char *const
export const k_pch_UserInterface_Screenshots_Bool: string = "screenshots";//char *const
export const k_pch_UserInterface_ScreenshotType_Int: string = "screenshotType";//char *const
export const k_pch_Notifications_Section: string = "notifications";//char *const
export const k_pch_Notifications_DoNotDisturb_Bool: string = "DoNotDisturb";//char *const
export const k_pch_Keyboard_Section: string = "keyboard";//char *const
export const k_pch_Keyboard_TutorialCompletions: string = "TutorialCompletions";//char *const
export const k_pch_Keyboard_ScaleX: string = "ScaleX";//char *const
export const k_pch_Keyboard_ScaleY: string = "ScaleY";//char *const
export const k_pch_Keyboard_OffsetLeftX: string = "OffsetLeftX";//char *const
export const k_pch_Keyboard_OffsetRightX: string = "OffsetRightX";//char *const
export const k_pch_Keyboard_OffsetY: string = "OffsetY";//char *const
export const k_pch_Keyboard_Smoothing: string = "Smoothing";//char *const
export const k_pch_Perf_Section: string = "perfcheck";//char *const
export const k_pch_Perf_PerfGraphInHMD_Bool: string = "perfGraphInHMD";//char *const
export const k_pch_Perf_AllowTimingStore_Bool: string = "allowTimingStore";//char *const
export const k_pch_Perf_SaveTimingsOnExit_Bool: string = "saveTimingsOnExit";//char *const
export const k_pch_Perf_TestData_Float: string = "perfTestData";//char *const
export const k_pch_Perf_GPUProfiling_Bool: string = "GPUProfiling";//char *const
export const k_pch_Perf_GpuBusMonitoring_Bool: string = "gpuBusMonitoring";//char *const
export const k_pch_CollisionBounds_Section: string = "collisionBounds";//char *const
export const k_pch_CollisionBounds_Style_Int32: string = "CollisionBoundsStyle";//char *const
export const k_pch_CollisionBounds_GroundPerimeterOn_Bool: string = "CollisionBoundsGroundPerimeterOn";//char *const
export const k_pch_CollisionBounds_CenterMarkerOn_Bool: string = "CollisionBoundsCenterMarkerOn";//char *const
export const k_pch_CollisionBounds_PlaySpaceOn_Bool: string = "CollisionBoundsPlaySpaceOn";//char *const
export const k_pch_CollisionBounds_FadeDistance_Float: string = "CollisionBoundsFadeDistance";//char *const
export const k_pch_CollisionBounds_WallHeight_Float: string = "CollisionBoundsWallHeight";//char *const
export const k_pch_CollisionBounds_ColorGammaR_Int32: string = "CollisionBoundsColorGammaR";//char *const
export const k_pch_CollisionBounds_ColorGammaG_Int32: string = "CollisionBoundsColorGammaG";//char *const
export const k_pch_CollisionBounds_ColorGammaB_Int32: string = "CollisionBoundsColorGammaB";//char *const
export const k_pch_CollisionBounds_ColorGammaA_Int32: string = "CollisionBoundsColorGammaA";//char *const
export const k_pch_CollisionBounds_EnableDriverImport: string = "enableDriverBoundsImport";//char *const
export const k_pch_Camera_Section: string = "camera";//char *const
export const k_pch_Camera_EnableCamera_Bool: string = "enableCamera";//char *const
export const k_pch_Camera_ShowOnController_Bool: string = "showOnController";//char *const
export const k_pch_Camera_EnableCameraForCollisionBounds_Bool: string = "enableCameraForCollisionBounds";//char *const
export const k_pch_Camera_RoomView_Int32: string = "roomView";//char *const
export const k_pch_Camera_BoundsColorGammaR_Int32: string = "cameraBoundsColorGammaR";//char *const
export const k_pch_Camera_BoundsColorGammaG_Int32: string = "cameraBoundsColorGammaG";//char *const
export const k_pch_Camera_BoundsColorGammaB_Int32: string = "cameraBoundsColorGammaB";//char *const
export const k_pch_Camera_BoundsColorGammaA_Int32: string = "cameraBoundsColorGammaA";//char *const
export const k_pch_Camera_BoundsStrength_Int32: string = "cameraBoundsStrength";//char *const
export const k_pch_Camera_RoomViewStyle_Int32: string = "roomViewStyle";//char *const
export const k_pch_audio_Section: string = "audio";//char *const
export const k_pch_audio_SetOsDefaultPlaybackDevice_Bool: string = "setOsDefaultPlaybackDevice";//char *const
export const k_pch_audio_EnablePlaybackDeviceOverride_Bool: string = "enablePlaybackDeviceOverride";//char *const
export const k_pch_audio_PlaybackDeviceOverride_String: string = "playbackDeviceOverride";//char *const
export const k_pch_audio_PlaybackDeviceOverrideName_String: string = "playbackDeviceOverrideName";//char *const
export const k_pch_audio_SetOsDefaultRecordingDevice_Bool: string = "setOsDefaultRecordingDevice";//char *const
export const k_pch_audio_EnableRecordingDeviceOverride_Bool: string = "enableRecordingDeviceOverride";//char *const
export const k_pch_audio_RecordingDeviceOverride_String: string = "recordingDeviceOverride";//char *const
export const k_pch_audio_RecordingDeviceOverrideName_String: string = "recordingDeviceOverrideName";//char *const
export const k_pch_audio_EnablePlaybackMirror_Bool: string = "enablePlaybackMirror";//char *const
export const k_pch_audio_PlaybackMirrorDevice_String: string = "playbackMirrorDevice";//char *const
export const k_pch_audio_PlaybackMirrorDeviceName_String: string = "playbackMirrorDeviceName";//char *const
export const k_pch_audio_OldPlaybackMirrorDevice_String: string = "onPlaybackMirrorDevice";//char *const
export const k_pch_audio_ActiveMirrorDevice_String: string = "activePlaybackMirrorDevice";//char *const
export const k_pch_audio_EnablePlaybackMirrorIndependentVolume_Bool: string = "enablePlaybackMirrorIndependentVolume";//char *const
export const k_pch_audio_LastHmdPlaybackDeviceId_String: string = "lastHmdPlaybackDeviceId";//char *const
export const k_pch_audio_VIVEHDMIGain: string = "viveHDMIGain";//char *const
export const k_pch_audio_DualSpeakerAndJackOutput_Bool: string = "dualSpeakerAndJackOutput";//char *const
export const k_pch_audio_MuteMicMonitor_Bool: string = "muteMicMonitor";//char *const
export const k_pch_Power_Section: string = "power";//char *const
export const k_pch_Power_PowerOffOnExit_Bool: string = "powerOffOnExit";//char *const
export const k_pch_Power_TurnOffScreensTimeout_Float: string = "turnOffScreensTimeout";//char *const
export const k_pch_Power_TurnOffControllersTimeout_Float: string = "turnOffControllersTimeout";//char *const
export const k_pch_Power_ReturnToWatchdogTimeout_Float: string = "returnToWatchdogTimeout";//char *const
export const k_pch_Power_AutoLaunchSteamVROnButtonPress: string = "autoLaunchSteamVROnButtonPress";//char *const
export const k_pch_Power_PauseCompositorOnStandby_Bool: string = "pauseCompositorOnStandby";//char *const
export const k_pch_Dashboard_Section: string = "dashboard";//char *const
export const k_pch_Dashboard_EnableDashboard_Bool: string = "enableDashboard";//char *const
export const k_pch_Dashboard_ArcadeMode_Bool: string = "arcadeMode";//char *const
export const k_pch_Dashboard_Position: string = "position";//char *const
export const k_pch_Dashboard_DesktopScale: string = "desktopScale";//char *const
export const k_pch_Dashboard_DashboardScale: string = "dashboardScale";//char *const
export const k_pch_Dashboard_UseStandaloneSystemLayer: string = "standaloneSystemLayer";//char *const
export const k_pch_Dashboard_StickyDashboard: string = "stickyDashboard";//char *const
export const k_pch_Dashboard_AllowSteamOverlays_Bool: string = "allowSteamOverlays";//char *const
export const k_pch_Dashboard_AllowVRGamepadUI_Bool: string = "allowVRGamepadUI";//char *const
export const k_pch_Dashboard_AllowVRGamepadUIViaGamescope_Bool: string = "allowVRGamepadUIViaGamescope";//char *const
export const k_pch_Dashboard_SteamMatchesHMDFramerate: string = "steamMatchesHMDFramerate";//char *const
export const k_pch_modelskin_Section: string = "modelskins";//char *const
export const k_pch_Driver_Enable_Bool: string = "enable";//char *const
export const k_pch_Driver_BlockedBySafemode_Bool: string = "blocked_by_safe_mode";//char *const
export const k_pch_Driver_LoadPriority_Int32: string = "loadPriority";//char *const
export const k_pch_WebInterface_Section: string = "WebInterface";//char *const
export const k_pch_VRWebHelper_Section: string = "VRWebHelper";//char *const
export const k_pch_VRWebHelper_DebuggerEnabled_Bool: string = "DebuggerEnabled";//char *const
export const k_pch_VRWebHelper_DebuggerPort_Int32: string = "DebuggerPort";//char *const
export const k_pch_TrackingOverride_Section: string = "TrackingOverrides";//char *const
export const k_pch_App_BindingAutosaveURLSuffix_String: string = "AutosaveURL";//char *const
export const k_pch_App_BindingLegacyAPISuffix_String: string = "_legacy";//char *const
export const k_pch_App_BindingSteamVRInputAPISuffix_String: string = "_steamvrinput";//char *const
export const k_pch_App_BindingOpenXRAPISuffix_String: string = "_openxr";//char *const
export const k_pch_App_BindingCurrentURLSuffix_String: string = "CurrentURL";//char *const
export const k_pch_App_BindingPreviousURLSuffix_String: string = "PreviousURL";//char *const
export const k_pch_App_NeedToUpdateAutosaveSuffix_Bool: string = "NeedToUpdateAutosave";//char *const
export const k_pch_App_DominantHand_Int32: string = "DominantHand";//char *const
export const k_pch_App_BlockOculusSDK_Bool: string = "blockOculusSDK";//char *const
export const k_pch_Trackers_Section: string = "trackers";//char *const
export const k_pch_DesktopUI_Section: string = "DesktopUI";//char *const
export const k_pch_LastKnown_Section: string = "LastKnown";//char *const
export const k_pch_LastKnown_HMDManufacturer_String: string = "HMDManufacturer";//char *const
export const k_pch_LastKnown_HMDModel_String: string = "HMDModel";//char *const
export const k_pch_LastKnown_ActualHMDDriver_String: string = "ActualHMDDriver";//char *const
export const k_pch_DismissedWarnings_Section: string = "DismissedWarnings";//char *const
export const k_pch_Input_Section: string = "input";//char *const
export const k_pch_Input_LeftThumbstickRotation_Float: string = "leftThumbstickRotation";//char *const
export const k_pch_Input_RightThumbstickRotation_Float: string = "rightThumbstickRotation";//char *const
export const k_pch_Input_ThumbstickDeadzone_Float: string = "thumbstickDeadzone";//char *const
export const k_pch_GpuSpeed_Section: string = "GpuSpeed";//char *const
export const IVRScreenshots_Version: string = "FnTable:IVRScreenshots_001";//char *const
export const IVRResources_Version: string = "FnTable:IVRResources_001";//char *const
export const IVRDriverManager_Version: string = "FnTable:IVRDriverManager_001";//char *const
export const k_unMaxActionNameLength: number = 64;//uint32_t
export const k_unMaxActionSetNameLength: number = 64;//uint32_t
export const k_unMaxActionOriginCount: number = 16;//uint32_t
export const k_unMaxBoneNameLength: number = 32;//uint32_t
export const k_nActionSetOverlayGlobalPriorityMin: number = 16777216;//int32_t
export const k_nActionSetOverlayGlobalPriorityMax: number = 33554431;//int32_t
export const k_nActionSetPriorityReservedMin: number = 33554432;//int32_t
export const IVRInput_Version: string = "FnTable:IVRInput_010";//char *const
export const k_ulInvalidIOBufferHandle: bigint = 0n;//uint64_t
export const IVRIOBuffer_Version: string = "FnTable:IVRIOBuffer_002";//char *const
export const k_ulInvalidSpatialAnchorHandle: SpatialAnchorHandle = 0;//uint32_t
export const IVRSpatialAnchors_Version: string = "FnTable:IVRSpatialAnchors_001";//char *const
export const IVRDebug_Version: string = "FnTable:IVRDebug_001";//char *const
export const k_ulDisplayRedirectContainer: PropertyContainerHandle = 25769803779n;//uint64_t
export const IVRProperties_Version: string = "FnTable:IVRProperties_001";//char *const
export const k_pchPathUserHandRight: string = "/user/hand/right";//char *
export const k_pchPathUserHandLeft: string = "/user/hand/left";//char *
export const k_pchPathUserHandPrimary: string = "/user/hand/primary";//char *
export const k_pchPathUserHandSecondary: string = "/user/hand/secondary";//char *
export const k_pchPathUserHead: string = "/user/head";//char *
export const k_pchPathUserGamepad: string = "/user/gamepad";//char *
export const k_pchPathUserTreadmill: string = "/user/treadmill";//char *
export const k_pchPathUserStylus: string = "/user/stylus";//char *
export const k_pchPathDevices: string = "/devices";//char *
export const k_pchPathDevicePath: string = "/device_path";//char *
export const k_pchPathBestAliasPath: string = "/best_alias_path";//char *
export const k_pchPathBoundTrackerAliasPath: string = "/bound_tracker_path";//char *
export const k_pchPathBoundTrackerRole: string = "/bound_tracker_role";//char *
export const k_pchPathPoseRaw: string = "/pose/raw";//char *
export const k_pchPathPoseTip: string = "/pose/tip";//char *
export const k_pchPathPoseGrip: string = "/pose/grip";//char *
export const k_pchPathSystemButtonClick: string = "/input/system/click";//char *
export const k_pchPathProximity: string = "/proximity";//char *
export const k_pchPathControllerTypePrefix: string = "/controller_type/";//char *
export const k_pchPathInputProfileSuffix: string = "/input_profile";//char *
export const k_pchPathBindingNameSuffix: string = "/binding_name";//char *
export const k_pchPathBindingUrlSuffix: string = "/binding_url";//char *
export const k_pchPathBindingErrorSuffix: string = "/binding_error";//char *
export const k_pchPathActiveActionSets: string = "/active_action_sets";//char *
export const k_pchPathComponentUpdates: string = "/total_component_updates";//char *
export const k_pchPathUserFootLeft: string = "/user/foot/left";//char *
export const k_pchPathUserFootRight: string = "/user/foot/right";//char *
export const k_pchPathUserShoulderLeft: string = "/user/shoulder/left";//char *
export const k_pchPathUserShoulderRight: string = "/user/shoulder/right";//char *
export const k_pchPathUserElbowLeft: string = "/user/elbow/left";//char *
export const k_pchPathUserElbowRight: string = "/user/elbow/right";//char *
export const k_pchPathUserKneeLeft: string = "/user/knee/left";//char *
export const k_pchPathUserKneeRight: string = "/user/knee/right";//char *
export const k_pchPathUserWristLeft: string = "/user/wrist/left";//char *
export const k_pchPathUserWristRight: string = "/user/wrist/right";//char *
export const k_pchPathUserAnkleLeft: string = "/user/ankle/left";//char *
export const k_pchPathUserAnkleRight: string = "/user/ankle/right";//char *
export const k_pchPathUserWaist: string = "/user/waist";//char *
export const k_pchPathUserChest: string = "/user/chest";//char *
export const k_pchPathUserCamera: string = "/user/camera";//char *
export const k_pchPathUserKeyboard: string = "/user/keyboard";//char *
export const k_pchPathClientAppKey: string = "/client_info/app_key";//char *
export const k_ulInvalidPathHandle: PathHandle = 0n;//uint64_t
export const IVRPaths_Version: string = "FnTable:IVRPaths_001";//char *const
export const IVRBlockQueue_Version: string = "FnTable:IVRBlockQueue_005";//char *
